name: notion_clone_frontend
description: "Notion Clone"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: "^3.6.0"
  flutter: ">=3.32.5"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  url_strategy: ^0.3.0
  dio: ^5.8.0+1
  json_serializable: ^6.9.0
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.34
  uuid: ^4.5.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.23.1

flutter:
  uses-material-design: true
  # assets:
  #   - env
  #   - assets/images/